import test from 'node:test';
import assert from 'node:assert/strict';
import { z } from 'zod';
import { QuestionSchema, VisualSchema } from '../src/engine/schema';
import { sampleDocument } from '../src/engine/sample';
import { normalizeLatex, formulaError, validateQuestion, syncVisuals, syncQuestionFromData, composeExam, exportErrors, answerText, fromLegacy, hash } from '../src/engine/core';
import { numericVariant, mutationErrors, adapterFor, createVariant } from '../src/engine/variant';
import { importText, detectFile } from '../src/engine/import';
import { cleanAndParseJSON } from '../src/services/fileExtractService';
import { shuffleSingleQuestion } from '../src/utils/shuffleExamUtils';
import { apiError } from '../api/ai';
import { AIQuestionDraftSchema, draftToQuestion } from '../src/engine/ai';
import { standaloneQuestionFormulas } from '../src/engine/export';

test('versioned question schema rejects malformed AI',()=>{assert.equal(QuestionSchema.safeParse({version:2,content:3}).success,false);assert.ok(z.toJSONSchema(QuestionSchema));});
test('visual schema rejects arbitrary SVG/remote image URLs',()=>{assert.equal(VisualSchema.safeParse({kind:'asset',dataUrl:'javascript:alert(1)'}).success,false);});
test('formula normalization supports powers/subscripts and chemistry charges',()=>{assert.equal(normalizeLatex('x² + H₂'),'x^{2} + H_{2}');assert.equal(formulaError(normalizeLatex('SO₄²⁻',true)),null);});
test('fractions roots matrices vectors integrals and greek render',()=>{for(const f of ['\\frac{1}{2}','\\sqrt{x}','x_1^2','\\vec{AB}','\\alpha + \\beta','\\int_0^1 x dx','\\begin{matrix}1&2\\\\3&4\\end{matrix}'])assert.equal(formulaError(f),null,f);assert.ok(formulaError('\\frac{1}{'));});
test('JSON parsing preserves genuine newline and escaped LaTeX',()=>{const value={text:'first\nsecond',latex:'\\frac{1}{2}'};assert.deepEqual(cleanAndParseJSON(JSON.stringify(value)),value);assert.throws(()=>cleanAndParseJSON('invalid'));});
test('old records normalize without new fields',()=>{const q=fromLegacy({id:'q',number:1,questionText:'What?',type:'multiple_choice',options:[{label:'A',text:'Yes'},{label:'B',text:'No'}],correctAnswer:'B'});assert.equal(answerText(q),'B');assert.equal(q.version,2);assert.deepEqual(q.visuals,[]);});
test('trộn option IDs keeps answer in 100 permutations',()=>{const doc=sampleDocument();for(let n=0;n<100;n++){const e=composeExam(doc,'001',true,true),q=e.questions.find(q=>q.id==='sample-chart')!;assert.equal(q.options.find(o=>o.id===q.correctAnswer.optionIds[0])!.text,'Địa điểm B');assert.equal(e.answerKey[q.id],answerText(q));}});
test('legacy shuffling keeps correct option identity when option text duplicates',()=>{const q:any={id:'q',number:1,type:'multiple_choice',questionText:'?',options:[{id:'first',label:'A',text:'same'},{id:'second',label:'B',text:'same'}],correctAnswer:'A'};for(let i=0;i<30;i++){const v=shuffleSingleQuestion(q,1);assert.equal(v.options!.find(o=>o.label===v.correctAnswer)!.id,'first');}});
test('true/false options are not shuffled independently of answer statements',()=>{const q:any={number:1,type:'true_false',options:[{label:'a',text:'x'},{label:'b',text:'y'}],correctAnswer:'a đúng b sai'};assert.deepEqual(shuffleSingleQuestion(q,2).options,q.options);});
test('stale geometry and labels fail then synchronize',()=>{const q=sampleDocument().questions[0];q.variables.AB.value=6;assert.ok(validateQuestion(q).errors.some(e=>e.includes('đồng bộ')));const synced=syncVisuals(q);const v=synced.visuals[0];assert.equal(v.kind,'geometry');if(v.kind==='geometry'){assert.equal(v.edges[0].label,'6');assert.equal(v.points[1].x,6);}assert.notEqual(q.visuals[0].dependencyHash,v.dependencyHash);});
test('table edits invalidate chart dependencies',()=>{const q=sampleDocument().questions[1];const before=q.visuals[0].dependencyHash;q.tables[0].rows[1][1]='250';assert.ok(validateQuestion(q).errors.some(e=>e.includes('đồng bộ')));assert.notEqual(syncVisuals(q).visuals[0].dependencyHash,before);});
test('numeric variants recalculate answer explanation geometry and keep source',()=>{const q=sampleDocument().questions[0];const result=numericVariant(q,7);assert.notEqual(result.content,q.content);assert.notEqual(result.correctAnswer.text,'5');assert.equal(result.validation.reviewed,false);assert.deepEqual(result.source,q.source);assert.equal(validateQuestion(result).valid,true);assert.ok(result.explanation.includes(result.correctAnswer.text));});
test('immutable facts and difficulty are enforced',()=>{const q=sampleDocument().questions[0];q.immutableFacts=['vuông tại A'];const next=structuredClone(q);next.content='Khác';next.difficulty='Khó';assert.equal(mutationErrors(q,next).length,2);assert.deepEqual(adapterFor('Lịch sử').strategies,['LANGUAGE_VARIANT']);});
test('segmentation keeps a/b parts with parent and detects options',()=>{const doc=importText('Câu 1. Chọn số\nA. Một\nB. Hai\nCâu 2. Tự luận\na) Tính\nb) Giải thích');assert.equal(doc.questions.length,2);assert.equal(doc.questions[0].options.length,2);assert.match(doc.questions[1].content,/b\)/);});
test('export blocks unreviewed or mismatched answers',()=>{const doc=sampleDocument(),e=composeExam(doc,'001');assert.ok(exportErrors(e).length>0);for(const q of e.questions){q.validation.reviewed=true;q.visuals.forEach(v=>v.needsReview=false);}assert.deepEqual(exportErrors(e),[]);e.answerKey[e.questions[0].id]='999';assert.ok(exportErrors(e).some(s=>s.includes('Bảng đáp án')));});
test('file type uses signature and enforces max size',async()=>{await assert.rejects(detectFile(new File(['not a pdf'],'exam.pdf',{type:'application/pdf'})));await assert.rejects(detectFile(new File(['%PDF-1.7'],'exam.png',{type:'image/png'})));assert.equal(await detectFile(new File(['%PDF-1.7'],'wrong.bin')),'application/pdf');await assert.rejects(detectFile(new File([],'empty.txt')));});
test('API error reports quota separately and never copies secret',()=>{const e=apiError({status:429,message:'secret-value'});assert.equal(e.code,'QUOTA_EXCEEDED');assert.ok(!e.message.includes('secret-value'));assert.equal(apiError({status:404}).code,'MODEL_UNAVAILABLE');});
test('dependency hash ignores object key ordering',()=>assert.equal(hash({b:2,a:1}),hash({a:1,b:2})));
test('manual content cannot silently disagree with variables and visual',()=>{
 const q=sampleDocument().questions[0];q.content=q.content.replace('AB = 3','AB = 6');q.validation.reviewed=true;
 assert.ok(validateQuestion(q).errors.some(e=>e.includes('Nội dung không khớp')));
 q.variables.AB.value=6;const next=syncQuestionFromData(q);
 assert.match(next.content,/AB = 6/);assert.equal(next.validation.reviewed,false);
 assert.equal(validateQuestion(next).valid,true);assert.ok(next.explanation.includes(next.correctAnswer.text));
 assert.equal(q.correctAnswer.text,'5','sync does not mutate the original');
});
test('stale explanation is rejected for constrained templates',()=>{
 const q=numericVariant(sampleDocument().questions[0],7);q.explanation='Đáp án là 5';
 assert.ok(validateQuestion(q).errors.some(e=>e.includes('Lời giải không khớp')));
});
test('explicit teacher answer headings are separated before option parsing',()=>{
 const doc=importText('Câu 1. Tính\nĐáp án: 5\nLời giải: Hai cộng ba.\nCâu 2. Chọn\nA. Một\nB. Hai\nĐáp án: B\nHai là đúng.');
 assert.equal(doc.questions[0].content,'Tính');assert.equal(doc.questions[0].correctAnswer.text,'5');
 assert.equal(doc.questions[0].explanation,'Hai cộng ba.');
 assert.equal(answerText(doc.questions[1]),'B');assert.equal(doc.questions[1].options[1].text,'Hai');
 assert.equal(doc.questions[1].validation.reviewed,false);
});
test('Gemini wire schema stays compact and maps into full QuestionModel',()=>{
 const wire=z.toJSONSchema(AIQuestionDraftSchema,{target:'draft-7'}),json=JSON.stringify(wire);
 assert.ok(json.length<6000);assert.ok(!json.includes('"default"'));assert.ok(!json.includes('"oneOf"'));
 const draft=AIQuestionDraftSchema.parse({subject:'Toán',grade:'9',topic:'Số học',difficulty:'Nhận biết',type:'single_choice',content:'$x^2$ bằng?',variables:[],formulas:[{rawSource:'x²',latex:'x^2',confidence:.95,kind:'math'}],tables:[],options:['1','2'],correctOptionIndexes:[1],answerText:'',explanation:'Theo dữ kiện.',immutableFacts:[],warnings:[]});
 const q=draftToQuestion(draft,{id:'ai-q',number:1,documentId:'doc'});
 assert.equal(q.correctAnswer.optionIds[0],'ai-q-o2');assert.equal(q.formulas[0].needsReview,false);assert.equal(QuestionSchema.safeParse(q).success,true);
 for(const indexes of [[2],[-1],[0,0]]) assert.throws(()=>draftToQuestion({...draft,correctOptionIndexes:indexes},{id:'ai-q',number:1,documentId:'doc'}));
 const variable={name:' x ',value:1,policy:'MUTABLE' as const,min:null,max:null,unit:''};
 assert.equal(draftToQuestion({...draft,variables:[variable]},{id:'ai-q',number:1,documentId:'doc'}).variables.x.value,1);
 for(const names of [['x',' x '],['__proto__'],['']]) assert.throws(()=>draftToQuestion({...draft,variables:names.map(name=>({...variable,name}))},{id:'ai-q',number:1,documentId:'doc'}));
 const original=sampleDocument().questions[0];
 const variant=draftToQuestion(draft,{id:original.id,number:1,documentId:'doc',original});
 for(const key of ['subject','grade','topic','difficulty','type'] as const) assert.equal(variant[key],original[key]);
});
test('answer and option formulas cannot leak into student question body',()=>{
 const q=sampleDocument().questions[0];
 q.content='Tính $\\frac{1}{2}+\\frac{1}{4}$.';
 q.explanation='Quy đồng: $\\frac{2}{4} + \\frac{1}{4} = \\frac{3}{4}$.';
 q.options=[{id:'a',text:'$\\frac{3}{4}$'}];
 const values=['\\frac{1}{2}+\\frac{1}{4}','\\frac{2}{4}+\\frac{1}{4}=\\frac{3}{4}','\\frac{3}{4}','x^2'];
 q.formulas=values.map((latex,i)=>({id:String(i),latex,rawSource:latex,confidence:1,needsReview:false,kind:'math'}));
 assert.deepEqual(standaloneQuestionFormulas(q).map(f=>f.latex),['x^2']);
});
test('AI variant requests include distinct seeds instead of sharing cached results',async()=>{
 const q=sampleDocument().questions[0];q.validation.reviewed=true;q.templates=undefined;q.solver=undefined;
 const requests:string[]=[];
 const provider={extract:async(doc:any)=>doc,validate:async()=>({valid:true,errors:[],warnings:[]}),generateVariant:async(original:any,strategy:string)=>{requests.push(strategy);return structuredClone(original);}};
 await createVariant(q,'NUMERIC_VARIANT',1,provider);await createVariant(q,'NUMERIC_VARIANT',2,provider);
 assert.match(requests[0],/variation seed 1/);assert.ok(requests.some(s=>s.includes('variation seed 2')));
});
