import { newDocument } from './import';
import { QuestionSchema } from './schema';
import { syncVisuals } from './core';
export function sampleDocument(){
 const doc=newDocument('Đề mẫu minh họa V2 — Toán và Địa lí');doc.metadata.subject='Đa môn';doc.metadata.grade='9';
 const q=QuestionSchema.parse({id:'sample-geometry',version:2,number:1,subject:'Toán',grade:'9',topic:'Định lý Pythagoras',difficulty:'Thông hiểu',type:'short_answer',source:{documentId:doc.id},content:'Tam giác ABC vuông tại A, AB = 3 cm, AC = 4 cm. Tính BC (cm).',originalContent:'Tam giác ABC vuông tại A, AB = 3 cm, AC = 4 cm. Tính BC (cm).',variables:{AB:{value:3,policy:'MUTABLE',min:3,max:12,unit:'cm'},AC:{value:4,policy:'MUTABLE',min:4,max:15,unit:'cm'}},templates:{content:'Tam giác ABC vuông tại A, AB = {{AB}} cm, AC = {{AC}} cm. Tính BC (cm).',answer:'{{answer}}',explanation:'Theo định lý Pythagoras, BC là căn bậc hai của tổng bình phương {{AB}} và {{AC}}, bằng {{answer}} cm.',options:{}},solver:{kind:'pythagoras',inputs:['AB','AC']},correctAnswer:{text:'5'},explanation:'Theo định lý Pythagoras, BC là căn bậc hai của tổng bình phương 3 và 4, bằng 5 cm.',visuals:[{id:'triangle',kind:'geometry',description:'Tam giác ABC vuông tại A (theo dữ kiện đề bài)',points:[{id:'A',x:0,y:0,label:'A'},{id:'B',x:3,y:0,label:'B',xVariable:'AB'},{id:'C',x:0,y:4,label:'C',yVariable:'AC'}],edges:[{from:'A',to:'B',label:'3',variable:'AB'},{from:'A',to:'C',label:'4',variable:'AC'},{from:'B',to:'C',label:'BC'}],constraints:[{type:'perpendicular',evidence:'Đề bài nêu tam giác vuông tại A.',refs:['A','B','C']}],dependencies:['variables.AB','variables.AC'],confidence:1,needsReview:true}],validation:{status:'needs_review',extractionConfidence:1,answerConfidence:1}});
 const chart=QuestionSchema.parse({id:'sample-chart',version:2,number:2,subject:'Địa lí',grade:'9',topic:'Đọc bảng số liệu',difficulty:'Nhận biết',type:'single_choice',source:{documentId:doc.id},content:'Bảng sau là số liệu giả định dùng cho bài tập. Địa điểm nào có lượng mưa lớn nhất?',originalContent:'Bảng sau là số liệu giả định dùng cho bài tập. Địa điểm nào có lượng mưa lớn nhất?',tables:[{id:'rain',headers:['Địa điểm','Lượng mưa (mm)'],rows:[['A','100'],['B','200'],['C','150']],caption:'Số liệu giả định',units:'mm'}],visuals:[{id:'rain-chart',kind:'chart',description:'Lượng mưa giả định theo địa điểm',tableId:'rain',chartType:'bar',labelColumn:0,valueColumn:1,confidence:1,needsReview:true,dependencies:['tables.rain']}],options:[{id:'rain-a',text:'Địa điểm A'},{id:'rain-b',text:'Địa điểm B'},{id:'rain-c',text:'Địa điểm C'}],correctAnswer:{optionIds:['rain-b']},explanation:'Địa điểm B có lượng mưa 200 mm, lớn nhất trong bảng.',validation:{status:'needs_review',extractionConfidence:1,answerConfidence:1}});
 doc.questions=[syncVisuals(q),syncVisuals(chart)];doc.warnings=['Đây là đề mẫu soạn sẵn để kiểm tra editor và export; không phải kết quả Gemini thực tế.'];return doc;
}
