import React from 'react';
import { MathContent } from './MathContent';
import type { QuestionModel, DocumentModel, VisualData } from '../engine/schema';
import { answerText, normalizeLatex, syncVisuals, validateQuestion } from '../engine/core';
import { visualSvg } from '../engine/visual';

export function VisualPreview({visual,q}:{visual:VisualData;q:QuestionModel}) {
  if(visual.hidden)return <p className="text-slate-500">Hình đang ẩn.</p>;
  try {return visual.kind==='asset'?<img className="max-h-96 max-w-full object-contain mx-auto" src={visual.dataUrl} alt={visual.description} loading="lazy"/>:<div className="v2-svg" dangerouslySetInnerHTML={{__html:visualSvg(visual,q)}}/>;}catch{return <p role="alert">Không dựng được hình. Kiểm tra bảng hoặc dữ kiện nguồn.</p>;}
}
export default function QuestionEditorV2({q,assets,onChange,onRestore}:{q:QuestionModel;assets:DocumentModel['assets'];onChange:(q:QuestionModel)=>void;onRestore?:()=>void}){
 const result=validateQuestion(q);
 const edit=(patch:Partial<QuestionModel>)=>onChange({...q,...patch,validation:{...q.validation,status:'needs_review',reviewed:false,errors:[]}});
 const editVisual=(index:number,patch:any)=>edit({visuals:q.visuals.map((v,i)=>i===index?{...v,...patch}:v)});
 return <article className="v2-question">
   <div className="v2-row"><h3>Câu {q.number}</h3><span className={result.valid&&q.validation.reviewed?'v2-good':'v2-warn'}>{result.valid&&q.validation.reviewed?'✓ Đã duyệt':'⚠ Cần kiểm tra'}</span><span className="text-slate-500 text-sm">{q.source.page?`Trang ${q.source.page}`:'Nguồn văn bản'} · {q.subject||'Chưa chọn môn'}</span></div>
   <div className="v2-grid"><label>Môn học<input value={q.subject} onChange={e=>edit({subject:e.target.value})}/></label><label>Lớp<input value={q.grade} onChange={e=>edit({grade:e.target.value})}/></label><label>Dạng câu<select value={q.type} onChange={e=>edit({type:e.target.value as QuestionModel['type']})}>{['single_choice','multiple_choice','true_false','short_answer','essay','fill_blank','matching','ordering','reading_comprehension','image_based','table_based','graph_based','compound_question','other'].map(t=><option key={t}>{t}</option>)}</select></label></div>
   <label>Nội dung câu {q.number}<textarea rows={4} value={q.content} onChange={e=>edit({content:e.target.value})}/></label>
   <div className="v2-preview"><MathContent content={q.content}/></div>
   {!!Object.keys(q.variables).length&&<details><summary>Dữ kiện và giới hạn biến đổi</summary><div className="v2-grid">{Object.entries(q.variables).map(([key,v])=><label key={key}>{key} ({v.unit||'không đơn vị'}) · {v.policy}<input type="number" value={v.value} onChange={e=>edit({variables:{...q.variables,[key]:{...v,value:Number(e.target.value)}}})}/><span className="text-sm">Giới hạn: {v.min??'chưa có'} – {v.max??'chưa có'}</span></label>)}</div><p>Thay biến sẽ yêu cầu kiểm tra lại nội dung, đáp án và hình.</p></details>}
   <details open={q.formulas.length>0}><summary>Công thức ({q.formulas.length})</summary>{q.formulas.map((f,i)=><div className="v2-subblock" key={f.id}><label>LaTeX {i+1}<input value={f.latex} onChange={e=>{const latex=e.target.value;edit({formulas:q.formulas.map((v,j)=>j===i?{...v,latex,needsReview:true}:v),content:q.content.split(f.latex).join(latex)});}}/></label><MathContent content={`$${f.latex}$`}/><button onClick={()=>edit({formulas:q.formulas.map((v,j)=>j===i?{...v,latex:normalizeLatex(v.rawSource,v.kind==='chemistry'),needsReview:true}:v)})}>Khôi phục nhận dạng</button><label><input type="checkbox" checked={f.kind==='chemistry'} onChange={e=>edit({formulas:q.formulas.map((v,j)=>j===i?{...v,kind:e.target.checked?'chemistry':'math',latex:normalizeLatex(v.rawSource,e.target.checked),needsReview:true}:v)})}/> Công thức Hóa học</label></div>)}<button onClick={()=>edit({formulas:[...q.formulas,{id:crypto.randomUUID(),rawSource:'',latex:'',confidence:0,needsReview:true,kind:'math'}]})}>+ Thêm công thức</button></details>
   <details open={q.tables.length>0}><summary>Bảng dữ liệu ({q.tables.length})</summary>{q.tables.map((t,ti)=><div className="v2-table-wrap" key={t.id}><label>Tên bảng<input value={t.caption} onChange={e=>edit({tables:q.tables.map((v,i)=>i===ti?{...v,caption:e.target.value}:v)})}/></label><table><thead><tr>{t.headers.map((h,ci)=><th key={ci}><input aria-label={`Tiêu đề cột ${ci+1}`} value={h} onChange={e=>edit({tables:q.tables.map((v,i)=>i===ti?{...v,headers:v.headers.map((x,j)=>j===ci?e.target.value:x)}:v)})}/></th>)}</tr></thead><tbody>{t.rows.map((r,ri)=><tr key={ri}>{r.map((c,ci)=><td key={ci}><input aria-label={`Bảng ${ti+1} dòng ${ri+1} cột ${ci+1}`} value={c} onChange={e=>edit({tables:q.tables.map((v,i)=>i===ti?{...v,rows:v.rows.map((row,j)=>j===ri?row.map((x,k)=>k===ci?e.target.value:x):row)}:v)})}/></td>)}</tr>)}</tbody></table></div>)}<button onClick={()=>edit({tables:[...q.tables,{id:crypto.randomUUID(),headers:['Đối tượng','Giá trị'],rows:[['A','1'],['B','2']],caption:'',units:'',mergedCells:[]}]})}>+ Thêm bảng để nhập dữ liệu</button></details>
   <details open={q.visuals.length>0}><summary>Hình và sơ đồ ({q.visuals.length})</summary>{q.visuals.map((v,vi)=><div className="v2-subblock" key={v.id}><VisualPreview visual={v} q={q}/><label>Mô tả hình<input value={v.description} onChange={e=>editVisual(vi,{description:e.target.value})}/></label><div className="v2-row"><button onClick={()=>editVisual(vi,{hidden:!v.hidden})}>{v.hidden?'Hiện hình':'Ẩn hình'}</button><button onClick={()=>onChange(syncVisuals({...q,validation:{...q.validation,reviewed:false,status:'needs_review'}}))}>Đồng bộ từ dữ kiện</button><button onClick={()=>edit({visuals:q.visuals.filter((_,i)=>i!==vi)})}>Gỡ khỏi câu</button></div>{(v.kind==='geometry'||v.kind==='diagram')&&(v.kind==='geometry'?v.points:v.nodes).map((p,pi)=><label key={p.id}>Nhãn {p.id}<input value={p.label} onChange={e=>editVisual(vi,v.kind==='geometry'?{points:v.points.map((n,i)=>i===pi?{...n,label:e.target.value}:n)}:{nodes:v.nodes.map((n,i)=>i===pi?{...n,label:e.target.value}:n)})}/></label>)}</div>)}
     {assets.length>0&&<label>Gắn ảnh gốc vào câu<select value="" onChange={e=>{const asset=assets.find(v=>v.id===e.target.value);if(asset)onChange(syncVisuals({...q,visuals:[...q.visuals,{...structuredClone(asset),id:crypto.randomUUID()}],validation:{...q.validation,reviewed:false,status:'needs_review'}}));}}><option value="">Chọn ảnh…</option>{assets.map(v=><option key={v.id} value={v.id}>{v.description}</option>)}</select></label>}
     {q.tables.length>0&&<button onClick={()=>onChange(syncVisuals({...q,visuals:[...q.visuals,{id:crypto.randomUUID(),kind:'chart',description:'Biểu đồ từ bảng dữ liệu',tableId:q.tables[0].id,labelColumn:0,valueColumn:1,chartType:'bar',confidence:1,needsReview:true,dependencies:[`tables.${q.tables[0].id}`],dependencyHash:'',hidden:false}],validation:{...q.validation,reviewed:false,status:'needs_review'}}))}>+ Biểu đồ từ bảng đầu tiên</button>}
   </details>
   <div className="v2-grid">{q.options.map((o,i)=><label key={o.id}>Phương án {String.fromCharCode(65+i)}<input value={o.text} onChange={e=>edit({options:q.options.map((v,j)=>j===i?{...v,text:e.target.value}:v)})}/><label><input type="checkbox" checked={q.correctAnswer.optionIds.includes(o.id)} onChange={e=>edit({correctAnswer:{...q.correctAnswer,optionIds:e.target.checked?(q.type==='single_choice'?[o.id]:[...q.correctAnswer.optionIds,o.id]):q.correctAnswer.optionIds.filter(id=>id!==o.id)}})}/> Đáp án đúng</label></label>)}</div>
   <button onClick={()=>edit({options:[...q.options,{id:crypto.randomUUID(),text:''}]})}>+ Thêm phương án</button>
   <label>Đáp án tự luận / trả lời ngắn<input value={q.correctAnswer.text} onChange={e=>edit({correctAnswer:{...q.correctAnswer,text:e.target.value}})}/></label><label>Lời giải<textarea rows={3} value={q.explanation} onChange={e=>edit({explanation:e.target.value})}/></label>
   <p>Đáp án hiện tại: <strong>{answerText(q)||'Chưa có'}</strong></p>
   {result.errors.map((e,i)=><p className="v2-error" role="alert" key={i}>✕ {e}</p>)}
   <div className="v2-row"><button className="v2-primary" disabled={!result.valid} onClick={()=>onChange({...q,formulas:q.formulas.map(f=>({...f,needsReview:false})),visuals:q.visuals.map(v=>({...v,needsReview:false})),validation:{...q.validation,reviewed:true,status:'ready',errors:[]}})}>Tôi đã đối chiếu nguồn, hình và đáp án</button>{onRestore&&<button onClick={onRestore}>Khôi phục câu gốc</button>}</div>
 </article>;
}
